combat-tag:
  enabled: true
  combat-duration: 20
  on-additional-combat: 2 # Adds this much more time to the combat duration. It cannot go over the combat duration

  kill-on-quit: true
  combat-tagged-message: "<aqua>You are now in combat with %otherPlayer%"
  combat-expired-message: "<green>You are no longer in combat"
  in-combat-action-bar: <aqua>You are in combat (<dark_aqua>%time_left%</dark_aqua>)

  # If it is enabled, a player's combat status ends the moment the opponent who tagged them leaves or dies.
  # If several players tagged them, it ends once the last of those opponents is gone.
  end-combat-when-opponent-gone: true

  command-block:
    enabled: true
    match-entire-words: false # If enabled the entire command must match

    blocked-message: "<red>You cannot run this command while on combat!"

    blocked-cmds:
      - /warp spawn
      - /home
      - /tpa
      - /tpahere
      - /spawn
      - /hub
      - /shop
      - /ah
      - /auctionhouse
      - /homes


explosive-disabler:
  crystals: false
  minecarts: false


stat-changer:
  # WARNING - This buffs from the item that is in the main hand, so that means if a player is holding a sword to use a crystal, it'll buff it based on the sword.
  # Currently, it also doesn't support specifying the level of the enchantment
  enabled: false

  items: # Add the items (or enchantments) you want to change the stats of.
    diamond_sword:
      type: BUFF # Buff or Nerf?

      # If you can't decide what damage you want it to do, you can turn on debug,
      # and it'll print out the original and final damage
      value: 20 # This means it will do +20 damage
    sharpness:
      type: buff
      value: 10

# This requires combat tag to be enabled
# Blocks players in combat from entering certain regions
# Requires WorldEdit
safe-zones:
  regions:

  block-message: "<red>You cannot go there while in combat!"
  in-safe-zone: "<red>You cannot get people into combat inside the safezone"

debug: false