name: "PvPCore"
version: "${version}"
authors:
  - SQD Studios

main: net.chamosmp.pvpcore.PvpcorePlugin

api-version: "1.21.11"
website: https://github.com/SQD-Studios/pvpcore

folia-supported: true


dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true